### ISSUE TITLE
Not output from voicecommand while aplay and others run just fine.

### ISSUE THREAD

**Issue by black-snow** [StevenHickson/PiAUISuite#45]
Hi,

I don't get voicecommand to talk to me. aplay and mpg123 work just fine, arecord, too. !hardware==plughw:0,0

Sometimes I get output like this:
```
Opening config file...
running in continuous mode
verifying command as well
keyword duration is 2 and duration is 3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 36597    0    14  100 36583      9  25085  0:00:01  0:00:01 --:--:-- 25091
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38689    0    14  100 38675      7  19478  0:00:01  0:00:01 --:--:-- 19483
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40122    0   234  100 39888     81  13942  0:00:02  0:00:02 --:--:-- 13941
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38668    0   185  100 38483     92  19318  0:00:01  0:00:01 --:--:-- 19318
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38144    0    14  100 38130      9  25881  0:00:01  0:00:01 --:--:-- 25903
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 36882    0    14  100 36868      9  25318  0:00:01  0:00:01 --:--:-- 25338
```

But nothing else happens. I don't hear anything during the setup.

Any guesses?

**Comment by Jeins98** [comment]
Same issues her. Please help

**Comment by black-snow** [comment]
@StevenHickson any suggestions?

**Comment by JBmiog** [comment]
Same here, the .mp3 returned from google's text to speech service are 0 bytes in size, I've checked this out and i'm getting a 503 http error when trying to use their TTS service.

**Comment by lemme** [comment]
Same here!

**Comment by StevenHickson** [comment]
This should be fixed if you do a git pull. Google started using a captcha for that url so I had to modify it slightly. 
Can anyone run UpdateAUISuite.sh or git pull and InstallAUISuite.sh voicecommand and confirm that it is fixed?

**Comment by Jeins98** [comment]
Thank you very much. I will test it when I arrive at home

**Comment by black-snow** [comment]
Sadly the update didn't fix anything for me. Still no sound while other applications output just fine.

Does the output on the console change when voicecommand has recognized the keyword? I'm still just getting the above console output.

**Comment by lemme** [comment]
me too - the update didn't fix the/my problem?!

**Comment by StevenHickson** [comment]
Did you run git pull?
Did you run UpdateAUISuite.sh?

It is working fine on multiple computers for me.Can you run just a test with tts:
tts "Testing a phrase 1 2 3"

**Comment by joepdooper** [comment]
The UpdateAUISuite.sh worked for me, thanks!

sudo /home/pi/PiAUISuite/Install/UpdateAUISuite.sh

**Comment by black-snow** [comment]
Alright, now it's talking to me during install and tts `test` runs fine. But it doesn't seem to recognize the keyword.

**Comment by Jeins98** [comment]
Thank you! Everything works fine.

**Comment by lemme** [comment]
I have got the same problem as black-snow...
... I run git pull
... I run UpdateAUISuite.sh
... I tested it with tts "Testing a phrase 1 2 3" - sound works fine
... I tested it with tts -l de "Hallo ich bin ein Schweinchen" - sound works fine too
... if I start voicecommand I get:
Opening config file...
Not querying for answers
running in continuous mode
verifying command as well
keyword duration is 3 and duration is 2
... if I say "pi" - nothing happen

Is there a solution?
greetz

**Comment by joepdooper** [comment]
Do 'voicecommand -e' and check your config file.

https://github.com/StevenHickson/PiAUISuite/issues/42

**Comment by black-snow** [comment]
@lemme guess we should make a new issue for that

**Comment by lemme** [comment]
@joepdooper 
thank you for the hint (#42) but there where no empty lines (I checked ".commands.conf" and "command.conf").

@black-snow 
do you have the same problems? did you start a new issue?

**Comment by black-snow** [comment]
@lemme no, I have not start a new one yet - feel free to do so

**Comment by ccurran689** [comment]
Has this issue been resolved? I've been trying to get this working for a week with no luck. I've ran all the updates and re-installed it countless times without being able to get any sound during install or when I run the actual program @black-snow @StevenHickson

**Comment by joepdooper** [comment]
Did you check your config file for empty lines through 'voicecommand-e'?
https://github.com/StevenHickson/PiAUISuite/issues/42

**Comment by ccurran689** [comment]
I did yes

**Comment by ccurran689** [comment]
@joepdooper There seems to be many with the same issue has no one resolved it? I've even tried an older version pi

**Comment by black-snow** [comment]
Gotta say that I haven't been trying for a while.

**Comment by ccurran689** [comment]
I've tried pretty much everything I can try so just keep and eye out for me if you can

**Comment by joepdooper** [comment]
Did it work before the update? Because that is the issue we are commenting on here…

**Comment by joepdooper** [comment]
Does $arecord/$aplay work for you?

**Comment by ccurran689** [comment]
Yep did indeed

**Comment by joepdooper** [comment]
Is your hardware set correct in your config?

**Comment by ccurran689** [comment]
Yeah I've used modprobe and tried changing the !hardwareplughw: to a few different settings just to check

**Comment by scooper86** [comment]
I too seem to have this issue, although have not yet played around with !hardwareplughw:

voicecommand setup does not recognise anything I say and comes back with symbols.

I am currently running Jessie and have also configured bluetooth a2dp so don't know if I have interfered with anything related to pulseaudio/asla.

**Comment by wildbi111** [comment]
I am having a similar issue in that voicecommand and tts do not work, yet aplay, arecord and mpg123 all work.  Any suggestions?
